development:
  adapter: mysql
  encoding: utf8
  collation: utf8_general_ci  
  reconnect: false
  database: backstage1_3dev
  pool: 5
  username: root
  password:
  host: localhost

production:
  adapter: mysql
  encoding: utf8
  collation: utf8_general_ci  
  reconnect: false
  database: backstage1_3dev
  pool: 5
  username: root
  password:
  host: localhost
  
launchpad:
  adapter: mysql
  encoding: utf8
  collation: utf8_general_ci
  reconnect: false
  database: launchpad1_0dev
  pool: 5
  username: root
  password:
  host: localhost
  
ref_area:
  adapter: mysql
  encoding: utf8
  collation: utf8_general_ci
  reconnect: false
  database: ref_area_dev
  pool: 5
  username: root
  password:
  host: localhost  